name: task_manager
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localized_locales: ^2.0.5
  intl: ^0.19.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  drift: ^2.21.0
  sqlite3_flutter_libs: ^0.5.25
  path_provider: ^2.1.4
  bloc_concurrency: ^0.2.5
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  rxdart: ^0.28.0
  uuid: ^4.5.1
  dio: ^5.1.0
  connectivity_plus: ^6.1.0
  device_info_plus: ^9.0.2
  jwt_decoder: ^2.0.1
  tuple: ^2.0.2
  auto_route: ^9.2.2
  json_annotation: ^4.8.1
  flutter_secure_storage: ^8.0.0
  get_it: ^7.7.0
  firebase_core: ^2.15.0
  firebase_messaging: ^14.4.0
  awesome_notifications: ^0.10.0
  flutter_svg: ^2.0.10+1
  flutter_map: ^7.0.2
  cached_network_image: ^3.4.1
  declarative_animated_list: ^0.2.0
  percent_indicator: ^4.2.3
  expandable_page_view: ^1.0.11
  tab_indicator_styler: ^2.0.0
  fl_chart: ^0.69.0
  boxy: ^2.1.0
  custom_timer: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  auto_route_generator: ^9.0.0
  freezed: ^2.3.1
  json_serializable: ^6.7.1
  drift_dev: ^2.1.0
  flutter_native_splash: ^2.2.19


flutter_native_splash:
  color: "#F0F2F5"
  color_dark: "#1F1D2C"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/svg/
  
  fonts:
    - family: Poppins
      fonts:
          - asset: assets/fonts/Poppins-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Poppins-Medium.ttf
            weight: 500
          - asset: assets/fonts/Poppins-Regular.ttf
            weight: 400
          - asset: assets/fonts/Poppins-Light.ttf
            weight: 300